services:

  postgres:
    image: postgres:17
    container_name: hams-postgres
    environment:
      POSTGRES_DB: hams_docker_db
      POSTGRES_USER: hams
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: hams-api
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: hams_docker_db
      DB_USERNAME: hams
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: hams-ui
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  postgres-data: